/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthSuppliersRouteRouteImport } from './routes/_auth/suppliers/route'
import { Route as AuthLegalRouteRouteImport } from './routes/_auth/legal/route'
import { Route as AuthEmailTemplatesRouteRouteImport } from './routes/_auth/email-templates/route'
import { Route as AuthProductsIndexRouteImport } from './routes/_auth/products/index'
import { Route as AuthOrdersIndexRouteImport } from './routes/_auth/orders/index'
import { Route as AuthCustomersIndexRouteImport } from './routes/_auth/customers/index'
import { Route as AuthAnalyticsIndexRouteImport } from './routes/_auth/analytics/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthSuppliersNewRouteImport } from './routes/_auth/suppliers/new'
import { Route as AuthProductsNewRouteImport } from './routes/_auth/products/new'

const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const AuthSuppliersRouteRoute = AuthSuppliersRouteRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLegalRouteRoute = AuthLegalRouteRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthEmailTemplatesRouteRoute = AuthEmailTemplatesRouteRouteImport.update({
  id: '/email-templates',
  path: '/email-templates',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProductsIndexRoute = AuthProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthOrdersIndexRoute = AuthOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCustomersIndexRoute = AuthCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAnalyticsIndexRoute = AuthAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuppliersNewRoute = AuthSuppliersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthSuppliersRouteRoute,
} as any)
const AuthProductsNewRoute = AuthProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/email-templates': typeof AuthEmailTemplatesRouteRoute
  '/legal': typeof AuthLegalRouteRoute
  '/suppliers': typeof AuthSuppliersRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/products/new': typeof AuthProductsNewRoute
  '/suppliers/new': typeof AuthSuppliersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/analytics/': typeof AuthAnalyticsIndexRoute
  '/customers/': typeof AuthCustomersIndexRoute
  '/orders/': typeof AuthOrdersIndexRoute
  '/products/': typeof AuthProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/email-templates': typeof AuthEmailTemplatesRouteRoute
  '/legal': typeof AuthLegalRouteRoute
  '/suppliers': typeof AuthSuppliersRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/products/new': typeof AuthProductsNewRoute
  '/suppliers/new': typeof AuthSuppliersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/analytics': typeof AuthAnalyticsIndexRoute
  '/customers': typeof AuthCustomersIndexRoute
  '/orders': typeof AuthOrdersIndexRoute
  '/products': typeof AuthProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_auth/email-templates': typeof AuthEmailTemplatesRouteRoute
  '/_auth/legal': typeof AuthLegalRouteRoute
  '/_auth/suppliers': typeof AuthSuppliersRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/products/new': typeof AuthProductsNewRoute
  '/_auth/suppliers/new': typeof AuthSuppliersNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/analytics/': typeof AuthAnalyticsIndexRoute
  '/_auth/customers/': typeof AuthCustomersIndexRoute
  '/_auth/orders/': typeof AuthOrdersIndexRoute
  '/_auth/products/': typeof AuthProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/email-templates'
    | '/legal'
    | '/suppliers'
    | '/login'
    | '/signup'
    | '/products/new'
    | '/suppliers/new'
    | '/api/auth/$'
    | '/analytics/'
    | '/customers/'
    | '/orders/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/email-templates'
    | '/legal'
    | '/suppliers'
    | '/login'
    | '/signup'
    | '/products/new'
    | '/suppliers/new'
    | '/api/auth/$'
    | '/analytics'
    | '/customers'
    | '/orders'
    | '/products'
  id:
    | '__root__'
    | '/_auth'
    | '/_guest'
    | '/_auth/email-templates'
    | '/_auth/legal'
    | '/_auth/suppliers'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_auth/'
    | '/_auth/products/new'
    | '/_auth/suppliers/new'
    | '/api/auth/$'
    | '/_auth/analytics/'
    | '/_auth/customers/'
    | '/_auth/orders/'
    | '/_auth/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_auth/suppliers': {
      id: '/_auth/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthSuppliersRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/legal': {
      id: '/_auth/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof AuthLegalRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/email-templates': {
      id: '/_auth/email-templates'
      path: '/email-templates'
      fullPath: '/email-templates'
      preLoaderRoute: typeof AuthEmailTemplatesRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/products/': {
      id: '/_auth/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthProductsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/orders/': {
      id: '/_auth/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthOrdersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/customers/': {
      id: '/_auth/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthCustomersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/analytics/': {
      id: '/_auth/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthAnalyticsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/suppliers/new': {
      id: '/_auth/suppliers/new'
      path: '/new'
      fullPath: '/suppliers/new'
      preLoaderRoute: typeof AuthSuppliersNewRouteImport
      parentRoute: typeof AuthSuppliersRouteRoute
    }
    '/_auth/products/new': {
      id: '/_auth/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthProductsNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthSuppliersRouteRouteChildren {
  AuthSuppliersNewRoute: typeof AuthSuppliersNewRoute
}

const AuthSuppliersRouteRouteChildren: AuthSuppliersRouteRouteChildren = {
  AuthSuppliersNewRoute: AuthSuppliersNewRoute,
}

const AuthSuppliersRouteRouteWithChildren =
  AuthSuppliersRouteRoute._addFileChildren(AuthSuppliersRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthEmailTemplatesRouteRoute: typeof AuthEmailTemplatesRouteRoute
  AuthLegalRouteRoute: typeof AuthLegalRouteRoute
  AuthSuppliersRouteRoute: typeof AuthSuppliersRouteRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  AuthProductsNewRoute: typeof AuthProductsNewRoute
  AuthAnalyticsIndexRoute: typeof AuthAnalyticsIndexRoute
  AuthCustomersIndexRoute: typeof AuthCustomersIndexRoute
  AuthOrdersIndexRoute: typeof AuthOrdersIndexRoute
  AuthProductsIndexRoute: typeof AuthProductsIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthEmailTemplatesRouteRoute: AuthEmailTemplatesRouteRoute,
  AuthLegalRouteRoute: AuthLegalRouteRoute,
  AuthSuppliersRouteRoute: AuthSuppliersRouteRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  AuthProductsNewRoute: AuthProductsNewRoute,
  AuthAnalyticsIndexRoute: AuthAnalyticsIndexRoute,
  AuthCustomersIndexRoute: AuthCustomersIndexRoute,
  AuthOrdersIndexRoute: AuthOrdersIndexRoute,
  AuthProductsIndexRoute: AuthProductsIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
